#.cj
driverClassName=com.mysql.cj.jdbc.Driver

#test
#url=jdbc:mysql://47.99.237.101:63306/scmj_match?useUnicode=true&characterEncoding=utf8&noAccessToProcedureBodies=true&allowMultiQueries=true
#username=root
#password=smzyroot123

#47.98.234.219 online wx.xcx
#url=jdbc:mysql://47.98.234.219:63306/scmj_user_data_wxxcx?useUnicode=true&characterEncoding=utf8&noAccessToProcedureBodies=true&allowMultiQueries=true
#username=smzywxxcxscmj
#password=ScmjWxxcx2019

#local
url=jdbc:mysql://47.99.237.101:63306/dzpk?useUnicode=true&characterEncoding=utf8&noAccessToProcedureBodies=true&allowMultiQueries=true&serverTimezone=UTC
username=root
password=smzyroot123

#À­Ã×²âÊÔ·þ
urlRummy=jdbc:mysql://52.66.184.99:63306/rummy_online?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
usernameRummy=rummy2020
passwordRummy=rummygame@2020

#local
#urlRummy=jdbc:mysql://127.0.0.1:3306/game_mahjong?useUnicode=true&characterEncoding=utf8&noAccessToProcedureBodies=true&allowMultiQueries=true&serverTimezone=UTC
#usernameRummy=root
#passwordRummy=123456
#urlRummy=jdbc:mysql://47.99.237.101:63306/rummy_game?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#usernameRummy=root
#passwordRummy=smzyroot123


initialSize=1
maxActive=20
minIdle=10
maxWait=60000

timeBetweenEvictionRunMillis=60000
minEvictableIdleTimeMillis=60000

validationQuery=SELECT 'x'
testWhileIdle=true
testOnBorrow=false
testOnReturn=false

removeAbandoned=true
removeAbandonedTimeout=1800